### ISSUE TITLE
bqnCrate display is blank (google chrome)

### ISSUE THREAD

**Issue by RedEmberCat** [mlochbaum/bqncrate#2]
https://mlochbaum.github.io/bqncrate/

Using Google Chrome, the page display is mostly blank. In the picture below, deleting the highlighted `div` fixes the problem. I believe there's another large blank div at the bottom of the page as well.

This problem does not occur with Microsoft Edge, but Microsoft Edge's only purpose in life is to allow users to download a non-Microsoft browser, so I'm not sure why I mention it.

https://i.imgur.com/Uwjdem1.png

**Comment by mlochbaum** [comment]
Doesn't appear on Chromium, and the source code doesn't have anything like this div. I think this is probably being inserted by a browser extension. Maybe a styling one based on the `color-scheme: auto`?

**Comment by mlochbaum** [comment]
The `div` rules like `background:#fff` do come from bqncrate.css, so this thing probably inserts the div into every page on the (bad) assumption that it will stay invisible.

**Comment by mlochbaum** [comment]
Switched to more specific styling as a possible workaround, although I still think you have a poorly designed extension that's causing the problem.

**Comment by mlochbaum** [comment]
RedEmberCat confirmed in chat that the workaround prevented this display issue.
